version: '2'
services:
    dev_server:
        image: node:12.13.0
        command: npm run start:dev
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - '3000:3000'
        extra_hosts:
            - "docker-vm:192.168.99.100"

    server_watcher:
        image: node:12.13.0
        command: npm run watch:server
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
